package app.fastdrive.android.data

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * Room's DAO code is generated by KSP and needs a real (or in-memory) SQLite implementation to
 * run against, which a plain JVM unit test doesn't provide. Robolectric supplies that Android
 * environment so this can still run as a fast local unit test instead of needing an emulator.
 */
@RunWith(RobolectricTestRunner::class)
class CachedFileDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var dao: CachedFileDao

    @Before
    fun setUp() {
        database = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            AppDatabase::class.java,
        ).allowMainThreadQueries().build()
        dao = database.cachedFileDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun upsertThenDeleteByIdLeavesTheOtherFile() = runBlocking {
        val fileA = CachedFile(
            id = "a",
            folder = "/",
            name = "a.txt",
            size = 10,
            contentType = "text/plain",
            changedAt = "2026-01-01T00:00:00Z",
        )
        val fileB = CachedFile(
            id = "b",
            folder = "/",
            name = "b.txt",
            size = 20,
            contentType = "text/plain",
            changedAt = "2026-01-01T00:00:00Z",
        )

        dao.upsertAll(listOf(fileA, fileB))
        dao.deleteByIds(listOf("a"))

        val remaining = dao.observeAll().first()
        assertEquals(listOf(fileB), remaining)
    }
}
